### ISSUE TITLE
setup.py fix for pip.req issue

### ISSUE THREAD

**Issue by sub7corp** [chenjr0719/Facebook-Page-Crawler#6]
in the setup.py headder you can fix the pip.req bug in setup by just a simple modification

BEFORE
from setuptools import setup, find_packages
from pip.req import parse_requirements
import os
AFTER
from setuptools import setup, find_packages
from pip._internal.req import parse_requirements
import os

**Comment by chenjr0719** [comment]
What version of `pip` did you use? This issue is caused by `pip` >= 10. I will make it compatible both in `pip` >= 10 and `pip` <= 9.0.3.
